### ISSUE TITLE
logo for login page and navbar

### ISSUE THREAD

**Issue by RyanGilreath** [categilreath/tn_naturalist#12]

**Comment by RyanGilreath** [comment]
logo put in for login

**Comment by chriscate** [comment]
logo looks good on login... any way to make it look more "integrated" into the page? right now it kinda looks like it's just floating there. maybe having it part of a login box in the middle of the screen or something? not sure the best way...

**Comment by RyanGilreath** [comment]
yeah for sure, was really must making sure I could get the custom css working and figure out where to put images in the directory for flask-admin

**Comment by chriscate** [comment]
Got it! Sounds good

**Comment by RyanGilreath** [comment]
ok got this looking better in the login page - in the box now

need to get login page centered with navbar switch
