### ISSUE TITLE
A nice style for the UI

### ISSUE THREAD

**Issue by RyanGilreath** [categilreath/tn_naturalist#16]

**Comment by RyanGilreath** [comment]
got the custom templates working for the student model views

Making it look pretty will be a work in progress but better understanding now of how to use bootstrap and custom the flask-admin/security templates

**Comment by RyanGilreath** [comment]
* Header on each view
* Sidebar thats full width of left side
* Sidebar that stretches to bottom
* Responsive sidebar that goes away when sliding
* Change colors to Green

**Comment by chriscate** [comment]
done
